// Public API types barrel.
//
// All API request/response shapes are aliased from `./generated.ts`
// (auto-generated by `make api-types` from `docs/openapi.json`,
// which is generated from the Go DTOs by `make swagger-docs`).
// Do NOT edit shapes here; edit the Go struct or its swaggo annotations
// and re-run the generator.
//
// Frontend-only helpers (literal unions, constants, view composites)
// live in `./types.handwritten.ts` and are re-exported below.
//
// Naming policy: this file uses the historic frontend names (e.g.
// `User` instead of `UserResponse`, `MfaVerifyRequest` instead of
// `MFAVerifyRequest`) so the migration to generated types stays
// invisible to consumers. New code should prefer the alias names
// declared here.

import type { components } from './generated';
import type {
  Gender,
  Role,
  FactorType,
  ChildAttendanceStatus,
  ContractProperties,
} from './types.handwritten';

type S = components['schemas'];

// Helper that overrides specific fields on a generated schema with
// stricter types (typically the literal-string unions above). Used to
// re-narrow what swaggo emits as `string`.
//
// `Override` keeps the field required. `OverrideOptional` keeps it
// optional. We can't infer optionality from T because TS spreads Omit
// in a way that loses the `?` modifier — pass the right helper instead.
type Override<T, K extends keyof T, V> = Omit<T, K> & { [P in K]: V };
type OverrideOptional<T, K extends keyof T, V> = Omit<T, K> & { [P in K]?: V };

// ============================================================
// Auth + sessions
// ============================================================

export type LoginRequest = S['LoginRequest'];
export type LoginFactorDescriptor = S['LoginFactorDescriptor'];
export type MfaVerifyRequest = S['MFAVerifyRequest'];
export type MfaChallengeRequest = S['MFAChallengeRequest'];
export type MfaChallengeResponse = S['MFAChallengeResponse'];

export type FactorResponse = Override<S['FactorResponse'], 'type', FactorType>;
export type FactorListResponse = S['FactorListResponse'];
export type FactorEnrolRequest = S['FactorEnrollRequest'];
export type FactorActivateRequest = S['FactorActivateRequest'];
export type FactorActivateResponse = S['FactorActivateResponse'];
export type FactorRegenerateRequest = S['FactorRegenerateRequest'];
export type FactorDeleteRequest = S['FactorDeleteRequest'];
export type FactorLabelUpdateRequest = S['FactorLabelUpdateRequest'];
export type TOTPEnrollmentPayload = S['TOTPEnrollmentPayload'];
export type WebAuthnEnrollmentPayload = S['WebAuthnEnrollmentPayload'];
export type BackupCodesPayload = S['BackupCodesPayload'];

export type ErrorResponse = S['ErrorResponse'];
export type MessageResponse = S['MessageResponse'];

// ============================================================
// Organizations + users
// ============================================================

export type Organization = S['OrganizationResponse'];
export type OrganizationCreateRequest = S['OrganizationCreateRequest'];
export type OrganizationUpdateRequest = S['OrganizationUpdateRequest'];

// User and create/update requests don't carry a role — role is per-membership
// (UserMembership, UserOrganizationResponse). The hand-written types added
// a role field incorrectly; consumers that read it relied on a field the
// backend never returns.
export type User = S['UserResponse'];
export type UserCreateRequest = S['UserCreateRequest'];
export type UserUpdateRequest = S['UserUpdateRequest'];
export type UserOrganizationResponse = Override<S['UserOrganizationResponse'], 'role', Role>;
export type UserMembership = Override<S['UserMembership'], 'role', Role>;
export type UserMembershipsResponse = S['UserMembershipsResponse'];
export type UserSession = S['UserSessionResponse'];
export type UserSessionsResponse = S['UserSessionsResponse'];
export type UserAddOrganizationRequest = Override<S['UserAddOrganizationRequest'], 'role', Role>;
export type UserOrganizationRoleUpdateRequest = Override<
  S['UserOrganizationRoleUpdateRequest'],
  'role',
  Role
>;
export type SetSuperAdminRequest = S['UserSetSuperAdminRequest'];

// ============================================================
// Employee / Child (no shared "Person" type — the spec inlines the
// shared fields into each concrete schema instead of exposing the
// embedded Go struct)
// ============================================================

export type Employee = Override<S['EmployeeResponse'], 'gender', Gender>;
export type EmployeeContract = S['EmployeeContractResponse'];
export type EmployeeCreateRequest = Override<S['EmployeeCreateRequest'], 'gender', Gender>;
export type EmployeeUpdateRequest = S['EmployeeUpdateRequest'];
export type EmployeeContractCreateRequest = S['EmployeeContractCreateRequest'];

// `school_entry_date`, `contracts` and `vouchers` are optional, and the spec now
// says so itself: openapi-fixer reads `omitempty` out of the Go source instead
// of asserting that every response field is always present. This used to need a
// hand-written correction here, and only `school_entry_date` ever got one --
// `contracts` and `vouchers` are omitted just as readily, and the types claimed
// otherwise for both.
export type Child = Override<S['ChildResponse'], 'gender', Gender>;
// The optionality of `properties` comes from the spec; what is still hand-made
// is the value type, which swaggo can only describe as `map[string]any`.
export type ChildContract = OverrideOptional<
  S['ChildContractResponse'],
  'properties',
  ContractProperties
>;
export type ChildCreateRequest = Override<S['ChildCreateRequest'], 'gender', Gender>;
export type ChildUpdateRequest = S['ChildUpdateRequest'];
export type ChildContractCreateRequest = OverrideOptional<
  S['ChildContractCreateRequest'],
  'properties',
  ContractProperties
>;
// Intent-based contract writes. Each names one thing a user can do, so a given
// payload always means the same thing — unlike the PUT these replace, where an
// omitted field cleared data on one code path and was inherited on another.
export type ChildContractCorrectRequest = OverrideOptional<
  S['ChildContractCorrectRequest'],
  'properties',
  ContractProperties
>;
export type ChildContractAmendRequest = OverrideOptional<
  S['ChildContractAmendRequest'],
  'properties',
  ContractProperties
>;
export type ChildContractAmendResponse = S['ChildContractAmendResponse'];
export type ChildContractBoundaryResponse = S['ChildContractBoundaryResponse'];
// Not narrowed on `properties`, matching EmployeeContractCreateRequest: employee
// properties are passed straight through from the form, and narrowing only one
// side of the create/amend pair makes the two incompatible.
export type EmployeeContractCorrectRequest = S['EmployeeContractCorrectRequest'];
export type EmployeeContractAmendRequest = S['EmployeeContractAmendRequest'];
export type EmployeeContractAmendResponse = S['EmployeeContractAmendResponse'];
export type EmployeeContractBoundaryResponse = S['EmployeeContractBoundaryResponse'];
export type ContractEndRequest = S['ContractEndRequest'];
export type ContractBoundaryMoveRequest = S['ContractBoundaryMoveRequest'];

export type ChildWithoutVoucherResponse = S['ChildWithoutVoucherResponse'];
export type VoucherSuggestion = S['ChildVoucherCreateRequest'];
export type ChildVoucher = S['ChildVoucherResponse'];
export type UnmatchedBillChild = S['UnmatchedBillChildResponse'];

// ============================================================
// Sections
// ============================================================

export type Section = S['SectionResponse'];
export type SectionCreateRequest = S['SectionCreateRequest'];
export type SectionUpdateRequest = S['SectionUpdateRequest'];

// ============================================================
// Pay plans + budget items
//
// Each resource has two shapes:
//   - List shape (PayPlan, BudgetItem) — returned by GET /…/list endpoints
//   - Detail shape (PayPlanDetail, BudgetItemDetail) — returned by GET /…/{id}
//     and includes nested children (periods, entries).
// ============================================================

export type PayPlan = S['PayPlanResponse'];
export type PayPlanDetail = S['PayPlanDetailResponse'];
export type PayPlanPeriod = S['PayPlanPeriodResponse'];
export type PayPlanEntry = S['PayPlanEntryResponse'];
export type PayPlanCreateRequest = S['PayPlanCreateRequest'];
export type PayPlanUpdateRequest = S['PayPlanUpdateRequest'];
export type PayPlanPeriodCreateRequest = S['PayPlanPeriodCreateRequest'];
export type PayPlanPeriodUpdateRequest = S['PayPlanPeriodUpdateRequest'];
export type PayPlanEntryCreateRequest = S['PayPlanEntryCreateRequest'];
export type PayPlanEntryUpdateRequest = S['PayPlanEntryUpdateRequest'];

export type BudgetItem = S['BudgetItemResponse'];
export type BudgetItemDetail = S['BudgetItemDetailResponse'];
export type BudgetItemEntry = S['BudgetItemEntryResponse'];
export type BudgetItemCreateRequest = S['BudgetItemCreateRequest'];
export type BudgetItemUpdateRequest = S['BudgetItemUpdateRequest'];
export type BudgetItemEntryCreateRequest = S['BudgetItemEntryCreateRequest'];
export type BudgetItemEntryUpdateRequest = S['BudgetItemEntryUpdateRequest'];

// ============================================================
// Government funding
//
// Same list/detail split as pay plans — GET /government-fundings returns
// the list shape, GET /government-fundings/{id} returns the detail shape
// with nested periods and total_periods count.
// ============================================================

export type GovernmentFunding = S['GovernmentFundingResponse'];
export type GovernmentFundingDetail = S['GovernmentFundingDetailResponse'];
// `GovernmentFundingPeriod` is the rich shape (with nested `properties`)
// returned inside GovernmentFundingDetail. The list endpoint returns the
// thinner `GovernmentFundingPeriodResponse` shape (no properties); we
// don't currently need a frontend alias for that.
export type GovernmentFundingPeriod = S['GovernmentFundingPeriod'];
export type GovernmentFundingProperty = S['GovernmentFundingPropertyResponse'];
export type GovernmentFundingCreateRequest = S['GovernmentFundingCreateRequest'];
export type GovernmentFundingUpdateRequest = S['GovernmentFundingUpdateRequest'];
export type GovernmentFundingPeriodCreateRequest = S['GovernmentFundingPeriodCreateRequest'];
export type GovernmentFundingPeriodUpdateRequest = S['GovernmentFundingPeriodUpdateRequest'];
export type GovernmentFundingPropertyCreateRequest = S['GovernmentFundingPropertyCreateRequest'];
export type GovernmentFundingPropertyUpdateRequest = S['GovernmentFundingPropertyUpdateRequest'];

// ============================================================
// Government funding bills
// ============================================================

export type GovernmentFundingBillPayment = S['GovernmentFundingBillAmount'];
export type GovernmentFundingBillRow = S['GovernmentFundingBillRowResponse'];
export type GovernmentFundingBillChild = S['GovernmentFundingBillChildResponse'];
export type GovernmentFundingBillResponse = S['GovernmentFundingBillResponse'];
export type GovernmentFundingBillPeriodListItem = S['GovernmentFundingBillPeriodListResponse'];
export type GovernmentFundingBillPeriodResponse = S['GovernmentFundingBillPeriodResponse'];

// ============================================================
// Funding comparison (per-bill vs computed amounts)
// ============================================================

export type FundingComparisonAmount = S['FundingComparisonAmount'];
export type BillAppearance = S['BillAppearance'];
export type FundingComparisonChild = S['FundingComparisonChild'];
export type FundingComparisonResponse = S['FundingComparisonResponse'];
export type FundingComparisonCategorySummary = S['FundingComparisonCategorySummary'];
export type FundingComparisonIssueSummary = S['FundingComparisonIssueSummary'];
export type FundingComparisonSummary = S['FundingComparisonSummary'];
export type FundingComparisonWrappedResponse = S['FundingComparisonWrappedResponse'];

// ============================================================
// Statistics: financial / staffing / occupancy / age
// ============================================================

export type FinancialBudgetItemDetail = S['FinancialBudgetItemDetail'];
export type FinancialFundingDetail = S['FinancialFundingDetail'];
export type FinancialSalaryDetail = S['FinancialSalaryDetail'];
export type FinancialDataPoint = S['FinancialDataPoint'];
export type FinancialResponse = S['FinancialResponse'];
export type CalculationWarning = S['CalculationWarning'];

export type StaffingHoursDataPoint = S['StaffingHoursDataPoint'];
export type StaffingHoursResponse = S['StaffingHoursResponse'];
export type EmployeeStaffingHoursRow = S['EmployeeStaffingHoursRow'];
export type EmployeeStaffingHoursResponse = S['EmployeeStaffingHoursResponse'];

export type OccupancyAgeGroup = S['OccupancyAgeGroup'];
export type OccupancySupplementType = S['OccupancySupplementType'];
export type OccupancyDataPoint = S['OccupancyDataPoint'];
export type OccupancyCareType = S['OccupancyCareType'];
export type OccupancyResponse = S['OccupancyResponse'];

export type AgeDistributionResponse = S['AgeDistributionResponse'];
export type AgeDistributionBucket = S['AgeDistributionBucket'];

export type ContractPropertyCount = S['ContractPropertyCount'];
export type ContractPropertiesDistributionResponse = S['ContractPropertiesDistributionResponse'];

// Step promotions

export type StepPromotion = S['StepPromotionResponse'];
export type StepPromotionsResponse = S['StepPromotionsResponse'];

// ============================================================
// Funding for individual children (estimate / report views)
// ============================================================

export type ChildFundingMatchedProp = S['ChildFundingMatchedProp'];
export type ChildFundingResponse = S['ChildFundingResponse'];
export type ChildrenFundingResponse = S['ChildrenFundingResponse'];

// ============================================================
// Attendance
// ============================================================

export type ChildAttendanceResponse = Override<
  S['ChildAttendanceResponse'],
  'status',
  ChildAttendanceStatus
>;
export type ChildAttendanceCreateRequest = Override<
  S['ChildAttendanceCreateRequest'],
  'status',
  ChildAttendanceStatus
>;
export type ChildAttendanceUpdateRequest = OverrideOptional<
  S['ChildAttendanceUpdateRequest'],
  'status',
  ChildAttendanceStatus
>;
export type ChildAttendanceDailySummaryResponse = S['ChildAttendanceDailySummaryResponse'];

// ============================================================
// Billing history
// ============================================================

export type ChildBillingHistoryEntry = S['ChildBillingHistoryEntryResponse'];
export type ChildBillingHistoryResponse = S['ChildBillingHistoryResponse'];
export type ChildBillingSummaryEntry = S['ChildBillingSummaryEntry'];
export type ChildrenBillingSummaryResponse = S['ChildrenBillingSummaryResponse'];

// ============================================================
// Forecast
//
// The scenario-input shapes are generated now. They used to be hand-written
// in types.handwritten.ts because ForecastRequest carried the persistence
// models, whose every field the generator marked required — a scenario child
// could not satisfy that type, so the store described one by hand and the page
// cast through `as unknown`. The request DTOs are real now, so these are
// aliases like everything else.
// ============================================================

export type ForecastRequest = S['ForecastRequest'];
export type ForecastResponse = S['ForecastResponse'];
export type ForecastChild = S['ForecastChildInput'];
export type ForecastChildContract = S['ForecastChildContractInput'];
export type ForecastEmployee = S['ForecastEmployeeInput'];
export type ForecastEmployeeContract = S['ForecastEmployeeContractInput'];

// ============================================================
// Audit log
// ============================================================

export type AuditLogResponse = S['AuditLogResponse'];

// ============================================================
// Re-export hand-written helpers (literal unions, constants, composites)
// ============================================================

export type {
  Gender,
  Role,
  FactorType,
  ChildAttendanceStatus,
  MismatchType,
  ContractProperties,
  AuditAction,
  ValidState,
  PaginationParams,
  PaginatedResponse,
  AuditLogListParams,
  DashboardStats,
} from './types.handwritten';
export { DEFAULT_PAGE_SIZE, LOOKUP_FETCH_LIMIT, VALID_STATES } from './types.handwritten';

// ============================================================
// Login response: hand-built discriminated union
// ============================================================
//
// The spec exposes both LoginResponse (status='authenticated') and
// LoginMFARequiredResponse (status='mfa_required') as separate
// schemas, but doesn't combine them as oneOf. We hand-roll the union
// so callers can use `if (resp.status === 'authenticated')` narrowing.

export type LoginSuccessResponse = S['LoginResponse'];
export type LoginMfaRequiredResponse = S['LoginMFARequiredResponse'];
export type LoginResponse = LoginSuccessResponse | LoginMfaRequiredResponse;
