package main

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/eenemeene/kitamanager-go/tools/report-pdf/internal/auth"
	"github.com/eenemeene/kitamanager-go/tools/report-pdf/internal/config"
	"github.com/eenemeene/kitamanager-go/tools/report-pdf/internal/pdf"
	"github.com/eenemeene/kitamanager-go/tools/report-pdf/internal/version"
)

func main() {
	cmd := config.NewRootCmd(run)
	if err := cmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run(cfg *config.Config) error {
	monthStr := cfg.MonthString()

	// Fetch the API version up front (cheap unauthenticated GET). The
	// Web version comes later — we read it from a `<meta>` tag in the
	// rendered page DOM during GenerateReport, which guarantees the
	// version we record is the one that actually rendered the print
	// pages (no parallel HTTP route to drift out of sync).
	apiVersion, err := auth.FetchAPIVersion(cfg.APIURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: could not fetch API version: %v\n", err)
		apiVersion = "unknown"
	}
	fmt.Printf("API version: %s\n", apiVersion)
	fmt.Printf("CLI version: %s\n", version.Version())

	fmt.Printf("Logging in as %s...\n", cfg.Email)
	cookies, err := auth.Login(cfg.APIURL, cfg.Email, cfg.Password, cfg.BaseURL)
	if err != nil {
		return fmt.Errorf("login failed: %w", err)
	}
	fmt.Printf("Login successful (%d cookies)\n", len(cookies))

	fmt.Println("Initializing PDF generator...")
	gen, err := pdf.NewGenerator(cookies, cfg.BaseURL)
	if err != nil {
		return fmt.Errorf("initializing PDF generator: %w", err)
	}
	defer gen.Close()

	var failed []string
	var generated []string
	for _, report := range cfg.Reports {
		fmt.Printf("Generating %s report for %s...\n", report, monthStr)
		if err := gen.GenerateReport(report, cfg.OrgID, monthStr, cfg.OutputDir); err != nil {
			fmt.Fprintf(os.Stderr, "  Failed: %v\n", err)
			failed = append(failed, report)
			continue
		}
		generated = append(generated, filepath.Join(cfg.OutputDir, fmt.Sprintf("%s-%s-%s.pdf", report, cfg.OrgID, monthStr)))
	}

	if len(failed) > 0 {
		return fmt.Errorf("failed reports: %v", failed)
	}

	// Pick the deliverable PDF: the merged file when multiple reports
	// were rendered, otherwise the single individual file.
	var deliverable string
	if len(generated) > 1 {
		combinedPath := filepath.Join(cfg.OutputDir, fmt.Sprintf("report-%s-%s.pdf", cfg.OrgID, monthStr))
		fmt.Printf("Merging %d reports into %s...\n", len(generated), combinedPath)
		if err := pdf.MergeFiles(generated, combinedPath); err != nil {
			return fmt.Errorf("merging PDFs: %w", err)
		}
		fmt.Printf("  Saved %s\n", combinedPath)
		deliverable = combinedPath
	} else if len(generated) == 1 {
		deliverable = generated[0]
	}

	// Stamp the colophon onto the deliverable's last page so any future
	// reader can see exactly which report-pdf + API combination produced
	// this PDF. The CLI version is baked at build time via -ldflags;
	// the API version came from /health above.
	if deliverable != "" {
		// gen captured the web version from the rendered DOM during
		// the loop above. If the frontend is at a version older than
		// this feature it'll be empty — show "unknown" rather than a
		// blank slot so the colophon stays readable.
		webVersion := gen.WebVersion()
		if webVersion == "" {
			webVersion = "unknown"
		}
		fmt.Printf("Web version: %s\n", webVersion)
		colophon := fmt.Sprintf("Generated by report-pdf %s · API %s · Web %s · %s",
			version.Version(), apiVersion, webVersion,
			time.Now().UTC().Format("2006-01-02 15:04 UTC"))
		if err := pdf.StampColophon(deliverable, colophon); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: could not stamp colophon: %v\n", err)
		}
	}

	fmt.Println("\nAll reports generated successfully!")
	return nil
}
