package main

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/eenemeene/kitamanager-go/tools/report-pdf/internal/auth"
	"github.com/eenemeene/kitamanager-go/tools/report-pdf/internal/config"
	"github.com/eenemeene/kitamanager-go/tools/report-pdf/internal/pdf"
	"github.com/eenemeene/kitamanager-go/tools/report-pdf/internal/version"
)

func main() {
	cmd := config.NewRootCmd(run)
	if err := cmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run(cfg *config.Config) error {
	monthStr := cfg.MonthString()

	// API version up front (cheap unauthenticated GET). The Web version
	// comes from a `<meta>` tag in the rendered DOM during the report
	// render itself — guarantees the version we record is the one that
	// actually rendered the page (no parallel HTTP route to drift).
	apiVersion, err := auth.FetchAPIVersion(cfg.APIURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: could not fetch API version: %v\n", err)
		apiVersion = "unknown"
	}
	fmt.Printf("API version: %s\n", apiVersion)
	fmt.Printf("CLI version: %s\n", version.Version())

	fmt.Printf("Logging in as %s...\n", cfg.Email)
	cookies, err := auth.Login(cfg.APIURL, cfg.Email, cfg.Password, cfg.BaseURL)
	if err != nil {
		return fmt.Errorf("login failed: %w", err)
	}
	fmt.Printf("Login successful (%d cookies)\n", len(cookies))

	fmt.Println("Initializing PDF generator...")
	gen, err := pdf.NewGenerator(cookies, cfg.BaseURL)
	if err != nil {
		return fmt.Errorf("initializing PDF generator: %w", err)
	}
	defer gen.Close()

	// Single navigation, single PDF. The combined /report/print page on
	// the frontend renders cover + all four sections with CSS-driven
	// page breaks, so we no longer need to render each section
	// separately and merge afterwards.
	deliverable := filepath.Join(cfg.OutputDir, fmt.Sprintf("report-%s-%s.pdf", cfg.OrgID, monthStr))
	fmt.Printf("Generating combined report for %s...\n", monthStr)
	if err := gen.GenerateCombinedReport(cfg.OrgID, monthStr, deliverable); err != nil {
		return fmt.Errorf("generate report: %w", err)
	}
	fmt.Printf("  Saved %s\n", deliverable)

	// Stamp the colophon onto the deliverable's last page so any future
	// reader can see exactly which report-pdf + API + Web combination
	// produced this PDF.
	webVersion := gen.WebVersion()
	if webVersion == "" {
		webVersion = "unknown"
	}
	fmt.Printf("Web version: %s\n", webVersion)
	colophon := fmt.Sprintf("Generated by report-pdf %s · API %s · Web %s · %s",
		version.Version(), apiVersion, webVersion,
		time.Now().UTC().Format("2006-01-02 15:04 UTC"))
	if err := pdf.StampColophon(deliverable, colophon); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: could not stamp colophon: %v\n", err)
	}

	fmt.Println("\nReport generated successfully!")
	return nil
}
